name: PORCUPINE test on a combination of Python versions and OS

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  os-python-compatibility:
    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'macos-latest', 'windows-latest' ]
        python: [ '3.8', '3.9', '3.10' ]
        
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}

    - name: Check Python version
      run: |
        which python3
        python3 --version

    - name: Install dependencies on Ubuntu
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libbz2-dev liblzma-dev libz-dev
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt
        pip install -e .

    - name: Install dependencies on macOS
      if: runner.os == 'macOS'
      run: |
        brew install bzip2 xz
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt
        pip install -e .

    - name: Install dependencies on Windows
      if: runner.os == 'Windows'
      run: |
        choco install r.project
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
        $env:Path += ';C:\Program Files\R\R-4.0.0\bin'
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt
        pip install -e .

    - name: Run the tests
      run: pytest tests
